# Generated by Django 3.1.2 on 2024-03-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='request_count',
            field=models.IntegerField(default=1),
        ),
    ]
